### ISSUE TITLE
Support for GxEPD2?

### ISSUE THREAD

**Issue by holgerlembke** [Xinyuan-LilyGO/LilyGo-T5-ink-series#1]
Hi.

Is there any support for GxEPD2?

**Comment by RalfJL** [comment]
Hi,

for the V2.2 it might be coming up.
See
https://forum.arduino.cc/index.php?topic=487007.msg4845514#msg4845514

**Comment by lewisxhe** [comment]
Support, as long as there is a driver in GxEPD2, it can be used. My warehouse is just a demonstration for some novices.

**Comment by holgerlembke** [comment]
I appreciate your great product support for some novices.
