### ISSUE TITLE
T5 V2.2 2.9" schematics is wrong

### ISSUE THREAD

**Issue by RalfJL** [Xinyuan-LilyGO/LilyGo-T5-ink-series#6]
Hi,
the schematics for the above boards seams to be wrong.
The red LED is on with
digitalWrite(26, LOW);
So I assume it has the same connection as all the other boards:
+ -> Resistor -> LED -> PIN26

**Comment by lewisxhe** [comment]
The green one is the power indicator, and the red one can be controlled by GPIO26. The green light can be removed if it is not needed.

**Comment by L-oled** [comment]
Hi @RalfJL , I was facing to similar issue on the same board when trying to debug with openOCD (issue to find JTAG pinout):
it seem that there is "differents" v2.2 revision of this board.... My board have a JP1 20 pin connectors pinout that corresponds to the one here: http://www.lilygo.cn/prod_view.aspx?TypeId=50061&Id=1397&FId=t3:50061:3
But I didn't manage to find schematics, including on this directory (v2.2 don't match). Except for JP1 pinout, my board looks like a v1.2
