### ISSUE TITLE
T5 V2.2 2.9" green LED can't be turned off

### ISSUE THREAD

**Issue by RalfJL** [Xinyuan-LilyGO/LilyGo-T5-ink-series#7]
Hi,
according to the schematics the green LED is hardwired and always on.

This is not very good, if you want to run the board on a battery.
There is a battery connector so I assume it was intended for low power consumption.
There should be a better way to disable the green LED, than cutting the resistor off the board.

Regards

**Comment by lewisxhe** [comment]
It is a power indicator and cannot be controlled by software, if you don't need to remove it.
